name: call-build

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - 'main'

jobs:
  call:
    permissions:
      contents: write
      packages: write
    uses: runlix/build-workflow/.github/workflows/build-on-call-v2.yml@main
    with:
      image_name: distroless-runtime
      dockerfile_path: Dockerfile
      build_context: .
    secrets: inherit
